import streamlit as st

st.set_page_config(page_title="Documentation", page_icon="ℹ️")

st.title("Model parameters and details")

st.markdown("""
This page contains details regarding the model used to compute the dialyzer clearance and its input parameters.
""")

st.header("Input parameters")

st.subheader(r"$Q_B$: blood blow rate")
st.write(
    r"Inlet blood flow rate to the dialyzer. It's measured in $ml/min$."
)
st.markdown("---")

st.subheader(r"$Q_D$: dialysate flow rate")
st.write(
    r"Inlet dialysate flow rate to the dialyzer. It's measured in $ml/min$."
)
st.markdown("---")

st.subheader(r"Aspect Ratio ($\theta$): dialyzer length to diameter ratio")
st.write("Dialyzer length to diameter ratio. Formula:")
st.latex(r"\theta = \frac{L}{D_{shell}}")
st.write(r"where $L$ and $D_{shell}$ are dialyzer length and shell-side diameter, respectively, both measured in $m$.")
st.markdown("---")

st.subheader("$L_P$: membrane hydraulic permeability")
st.write(
    r"Membrane permeability to water, measured in $ml/(m^{2}{\cdot}h{\cdot}mmHg)$."
)
st.markdown("---")

st.subheader(r"Porosity ($\varepsilon$): porosity of the dialyzer")
st.write("Porosity of the dialyzer, equal to the free volume in the shell side. Adimensional quantity. Formula:")
st.latex(r"\varepsilon = 1-\frac{V_m}{V_{tot}} = 1-\frac{Nd_{ext}^2}{D_{shell}^2}")
st.write(r'''where $V_m = \pi$ is the volume occupied by membranes, $V_{tot}$ is the total volume of the dialyzer in the shell side, 
         $d_{ext}$ is the fiber external diameter in $m$ and $N$ is the number of fibers in the dialyzer.''')
st.markdown("---")

st.subheader(r"$P_B$: blood pressure")
st.write(
    r'''Blood outlet pressure, measured in $Pa$. This pressure has to be interpreted as relative to the dialysate outlet pressure, arbitrarily set to zero. 
    This could be done since both blood and dialysate were treated as incompressible fluids.'''
)
st.markdown("---")

st.subheader(r"$k_m$: urea mass transfer coefficient")
st.write(
    "Urea mass transfer coefficient, measured in $m/s$."
)
st.markdown("---")

st.subheader(r"$A_m$: membrane area")
st.write("Dialyzer membrane area referred to the external diameter. Formula:")
st.latex(r"A_m = N{\pi}d_{ext}L")
st.markdown("---")

st.info("Default values indicated in the visualizer app represent a typical use case.")

st.header("Model details")

st.write('''The urea clearance shown in the visualizer app is computed through a fourth-degree polynomial regression model 
         trained on synthetic data generated by a first-principles one-dimensional model of the dialyzer. The first-principles model 
         computes the clearance by solving mass balances and transport equations, obtaining pressure, concentration and flow rate profiles. 
         The model takes into account both diffusive and convective transport of urea. ''')

url = "http://dx.doi.org/10.1007/978-3-032-00652-3_19"
st.write("For more information about the model, check the published [article](%s)." % url)

